### ISSUE TITLE
Published package contains no code

### ISSUE THREAD

**Issue by pbelbin** [sparksuite/waterfall-cli#149]
Within a client project, using `waterfall-cli` version 0.3.0, I am seeing:

```
internal/modules/cjs/loader.js:300
      throw err;
      ^

Error: Cannot find module '/Users/peterbelbin/gitlab/spark/node_modules/waterfall-cli/dist/index.js'. Please verify that the package.json has a valid "main" entry
.
.
.

code: 'MODULE_NOT_FOUND',
  path: '/Users/peterbelbin/gitlab/spark/node_modules/waterfall-cli/package.json',
  requestPath: 'waterfall-cli'
```

The waterfall-cli package.json file has a 'main' entry, which directs towards 'dist/index.js` (which does not exist).

I compared the contents of the 0.2.0 against 0.3.0.

0.2.0 has the 'main' property set to 'src/index.js', and has the 'src' folder within it (with JavaScript files).
0.3.0 has the 'main' property set to 'dist/index.js', but, has no 'dist' folder.

**Comment by WesCossick** [comment]
@pbelbin Can you look to see if there is a misconfiguration in the [.travis.yml](https://github.com/sparksuite/waterfall-cli/blob/master/.travis.yml) file?

Also, be sure to label newly created issues appropriately.
