### ISSUE TITLE
Remove `error()`, add `printError()`

### ISSUE THREAD

**Issue by pbelbin** [sparksuite/waterfall-cli#334]
In order to avoid some issues to do with `error()` being called from sync vs async contexts, we've decided to unbundle what `error()` used to do, and make it just be about printing an error message in a standardized way, and to make the calling side responsible for what else happens in response to an error condition having been detected.

ie: 

- flushing of `stdout` before printing the error to `stderr`  
- calling `process.exit(255)` (which, used within async context, would *not* immediately cause program termination)

**Comment by WesCossick** [comment]
This should also resolve #178.

**Comment by WesCossick** [comment]
Just a note: we'll need to update the README as part of this change.
