### ISSUE TITLE
Hyphenated flags are not supported correctly

### ISSUE THREAD

**Issue by pbelbin** [sparksuite/waterfall-cli#367]
If I want to define a hyphenated flag (eg: 'no-start'), I need to define the `.spec.ts` as:

```ts
export interface Input {
   flags: {
      'no-start'?: boolean;
   };
}

const spec: CommandSpec<Input> = {
   description: 'Do something',
   flags: {
      'no-start': {
         description: 'Skip the start step',
      },
   },
};

export default spec;
```

But, when I then use this, and output the received data object, I see:

```json
flags: {
   noStart: true
}
```

The `no-start` has been transformed into `noStart`.

Seems good, but, if I define the interface (above) instead with:

```ts
   noStart?: boolean,
```

I receive an error message, complaining that `noStart` does not match up with anything in the spec (it's expecting `no-start`).

```
@sparksuite/cli:   Object literal may only specify known properties, and ''no-start'' does not exist in type
```

The issue seems to stem from the items in the list of descriptions *not* being translated from camel case into kebab case before being displayed.

**Comment by WesCossick** [comment]
Hmm, I don't think there's going to be any way to convert hyphenated flags/options to camelcase, while _also_ preserving strict type safety. Maybe we shouldn't be converting the names to camel case?

**Comment by pbelbin** [comment]
> Hmm, I don't think there's going to be any way to convert hyphenated flags/options to camelcase, while _also_ preserving strict type safety. Maybe we shouldn't be converting the names to camel case?

Sounds fine to me, to leave them 'as supplied'.  It will make the doings of Waterfall CLI less mysterious!

**Comment by WesCossick** [comment]
Agreed, sounds good!
