### ISSUE TITLE
Incorrect type definition for `data.accepts` and `options.accepts`

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/waterfall-cli#374]
The `data.accepts` type is defined as:

```ts
/** A finite array of acceptable data values or callback providing same. Invalid data will be rejected. */
accepts: NonNullable<Input['data']> extends
	| string[]
	| number[]
	| (() => string[] | number[])
	| (() => Promise<string[] | number[]>)
	? Input['data'] | (() => Promise<Input['data']>)
	: ExcludeMe;
```

However, there are two problems with this:

1. `Input['data']` shouldn't ever be defined as a function.
2. If `data.accepts` is defined as a function, it needs to be possible to be synchronous.

With these two problems in mind, I believe the type definition needs to be:

```ts
/** A finite array of acceptable data values or callback providing same. Invalid data will be rejected. */
accepts: NonNullable<Input['data']> extends
	| string[]
	| number[]
	? Input['data'] | (() => Input['data']) | (() => Promise<Input['data']>)
	: ExcludeMe;
```

**Comment by WesCossick** [comment]
It seems these problems plague `options.accepts` as well; I've updated the title accordingly.

**Comment by pbelbin** [comment]
If I use the suggestion you've provided, it creates a situation where, if the `interface Input.data` is a singular rather than array, then for `spec.data.accepts`, it expects nothing to be provided at all.

But, from what I understand, this *should* still accept an array of whichever type was stipulated for `Input.data`, ie: to allow a single item to be chosen from a set of possibilities.

Please confirm.

<img width="890" alt="Screen Shot 2021-07-06 at 4 23 53 PM" src="https://user-images.githubusercontent.com/10079005/124668880-21887e80-de77-11eb-8455-b09bbe421cce.png">


Perhaps the indicator for accepting multiple values from the list should be implied by the `interface Input.data` being an Array vs singular, but that's more to do with #373.

**Comment by WesCossick** [comment]
In reviewing the PR where we started accepting callback functions for `accepts`, and the way the spec object's `accepts` property works, I think we've got a poorly designed type here...

Here's what I'd expect, let me know if this seems accurate to you:

If the `Input['data']` property is a `string` or `number`, then I'd expect the `spec.data.accepts` property to be defined as either a callback function or to not have any `accepts` property (so it's a free response).

If the `Input['data']` property is a `string[]` or `number[]`, then I'd expect the same as above, but for `acceptsMultiple` to be `true`. This would probably need to be implemented alongside #373.

If the `Input['data']` property is a union type, like `'a' | 'b' | 'c'` or `1 | 2 | 3`, then I'd expect the `spec.data.accepts` property to be defined as an array of hardcoded strings (not a callback).

If the `Input['data']` property is a union type _and_ an array, like `('a' | 'b' | 'c')[]` or `(1 | 2 | 3)[]`, then I'd expect the same as above, but for `acceptsMultiple` to be `true`. This would also probably need to be implemented alongside #373.

**Comment by pbelbin** [comment]
Hmmmm.  Yeah, that's a bit more tightly defined than what I was thinking.  

It makes sense to only allow the use of a callback function when the `Input['data']` is not concretely defined.

In this case, since it's all about defining the response to the shape of the `Input` interface, it might be better to address all the needs at once rather than doing it progressively.

**Comment by pbelbin** [comment]
I've been working on this, and it strikes me that in the last case, it's really about unioned literals, which got me to wondering about needing to support a single literal.  I *presume* that the intent is to never support something like 
`'hello' | string | number`.  If there was a combination of such things, I'm guessing we should reject it if possible.

**Comment by WesCossick** [comment]
We'll still need to properly support optional `accepts` values. That would be defined in the `Input` object by using `?:` instead of `:`.

**Comment by WesCossick** [comment]
Right, we shouldn't ever support something like `'hello' | string | number`. If it's possible to block something like that via TypeScript, that's great; otherwise, we should just ignore that scenario since it's incorrect usage.

**Comment by pbelbin** [comment]
Regarding:

> If the Input['data'] property is a string or number, then I'd expect the spec.data.accepts property to be defined as either a callback function or to not have any accepts property (so it's a free response).
>
>If the Input['data'] property is a string[] or number[], then I'd expect the same as above, but for acceptsMultiple to be true. This would probably need to be implemented alongside #373.

I suspect this should *also* allow an array of values, in addition to being either a sync or async callback result.

eg:

If the Input['data'] property is a string or number, then I'd expect the spec.data.accepts property to be defined as either an array of values, possibly obtained by callback (sync or async), or, to not have any accepts property (so it's a free response)

**Comment by WesCossick** [comment]
That sounds mostly right. Just keep in mind that, if the spec file's `accepts` property contains an array (not a callback), then we know the values are hardcoded and we'll want the `Input['data']` type to be hardcoded too (e.g., it should be a union of string literals or number literals, like `'a' | 'b' | 'c'`).

**Comment by pbelbin** [comment]
Hmmm.  

I kind of feel like by not providing this ability, we're effectively saying that if the list of values are knowable without a callback, they *must* be hardcoded.

When the data is not knowable until execution time, it makes sense to me, to use a callback to allow the list to be defined.
But, at the same time, we are *forcing* the use of a callback when it's not always required.

eg:

If a tool, using Waterfall-CLI has the ability to format multiple types of files, and the formatters are organized using a sub-folder per file type, it's *possible* for the current list of supported file types to be hardcoded, but, for long-term ease of extending, instead, it's dynamically cataloging and building an array of supported file types, and this is available without the need for a callback.  The list *could* be defined statically, but, it would have to be updated by hand if another file type is added, which is undesirable, as it means there's another thing that has to be maintained.

Without making this change, we are *forcing* the array generation to be put inside a callback when it really doesn't need to be.

**Comment by WesCossick** [comment]
Okay, so @pbelbin and I hashed this out in-person. In summary, the specific situation that is not currently being accounted for is when inline code is executed and resolves to an array at variable initialization.

Take, for example, this code:

```ts
// Import type
import { CommandSpec } from 'waterfall-cli';

// Input
export interface Input {
    data?: number;
}

// Define and export spec
const spec: CommandSpec<Input> = {
    data: {
        accepts: (() => [Math.random(), Math.random()])(),
    }
};
export = spec;
```

The acceptable values are _not_ known in advance, but the `accepts` value also isn't a callback function. We can't change `Input['data']` to a union of numeric literals, which is what my previous design would have required.

_The above code snippet is overly simplified. There are more complex examples within some of our own internal codebases that are more complex._
