### ISSUE TITLE
Ability to distinctly control spacing of internally generated vs client-generated output

### ISSUE THREAD

**Issue by pbelbin** [sparksuite/waterfall-cli#382]
The options that control vertical space 'before' and 'after' do not offer any differentiation between whether the spacing is for Waterfall CLI generated output versus that which is sourced from the 'client' code.

It is desirable to have this differentiation to allow more fine-grained control of the appearance of the output.

eg:

```ts
interface options {
   spacing?: {
      before: number;
      after: number;
      self?: {
         before: number;
         after: number;
      }
   }
}
```

This way, the code emitting internally-controlled output can check `options.spacing.self[before|after|` before looking at `options.spacing[before|after]` for the values to use.

**Comment by pbelbin** [comment]
It might be, that the `spacing.self.[before|after]` should be considered as 'additional spacing' rather than total spacing.

**Comment by WesCossick** [comment]
This is probably not something we'll change about Waterfall CLI. I want the operation to be simple, so avoiding extraneous options helps achieve that goal. The intention is for the amount of before/after spacing to be consistent regardless of what is being outputted, and whether that output is produced by Waterfall CLI or commands it executes.

**Comment by pbelbin** [comment]
Ok, well, that's your choice.

Here is how the output looked using the code I put together as a proof:

<img width="1536" alt="Screen Shot 2021-08-23 at 10 02 54 AM" src="https://user-images.githubusercontent.com/10079005/130471968-2b6e94a5-3644-481b-85ad-beeeaba30bcc.png">
