### ISSUE TITLE
Provide callback that's called *before* `accepts` processing happens

### ISSUE THREAD

**Issue by pbelbin** [sparksuite/waterfall-cli#386]
Within the *.spec.* files, I'm providing a callback function for the `accepts`, which itself is async (because I'm calling other async functions within the callback).

Within each of these `accepts` callback functions, I'm having to duplicate some 'setup' type activity, because I don't know if/when the `accepts` will be called.

It would be really good to have some kind of very early `onLoad()` or `onInit()` kind of callback integration point that *always* is invoked *before* any of the `accepts` callbacks in the *.spec.* files are called.

This should be in addition to the existing `onStart()`, which happens *after* we know that we are not doing any `help` or `version` responses, so that the required setup details in support of `help` functionality can be done without performing yet, any actual application related functionality.

Multiple 'phases', if you like.  Perhaps calling `onStart()` but passing in a numeric to identify which 'phase' it's in, so that it only does what's necessary to that point?

**Comment by WesCossick** [comment]
I think the idea of an `onInit()` could completely replace the current `onStart()` function. Having two options with similar names and slightly different timing might be confusing.

**Comment by pbelbin** [comment]
What do you think about the idea then, of calling `onInit()` multiple times, with an argument that indicates whether it's before the 'help' is being processed versus after?

ie: for 'before-help', just configure what's needed, then, for `after-help`, we can do other work that's common to all commands.

**Comment by WesCossick** [comment]
Thinking about this more; why not just move the code before calling `waterfall.init()`? Then we wouldn't need to change anything in Spark.

**Comment by pbelbin** [comment]
We can't do that currently, because all of that functionality we need is tied to `async` code, which we can not exercise before calling `waterfall.init()`

**Comment by WesCossick** [comment]
Why can't we exercise async code before calling `waterfall.init()`?

**Comment by pbelbin** [comment]
Hmmmm.  Well, this comes down to how `async` functionality gets delayed until *after* the synchronous code is done, and is then processed according to the vagaries of how NodeJS handles it's pending async requests.

eg:

```ts
async function configureProjectPath() {
	if (await project.isValidPath(process.cwd())) {
		process.env.PROJECT_PATH = process.cwd();
	}
}

void configureProjectPath();

console.log('project path is: ', process.env.PROJECT_PATH);

```

when this is executed within what is considered a 'project', here is the output:

```
peterbelbin@Peters-MBP-2 main-stack-v5 % spark-v5 build --help
project path is:  undefined
```

**Comment by WesCossick** [comment]
If Waterfall CLI is being used in a context where top-level async/await isn't available, then you'd just need to wait to call `waterfall.init()` like this:

```ts
function sleep(ms:number) {
	return new Promise(resolve => setTimeout(resolve, ms));
}

async function configure() {
	await sleep(1000);
	process.env.PROJECT_PATH = process.cwd();
}

configure().then(() => {
	void waterfall.init();
});
```

**Comment by pbelbin** [comment]
hmmmm.  Yeah, I guess that will work in this case.
