### ISSUE TITLE
Integrate TypeScript

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/waterfall-cli#95]
We should first focus on integrating TypeScript and updating Travis CI's configuration as necessary to support it. We shouldn't worry yet about rewriting the code from vanilla JS to TypeScript. That will be another issue.

**Comment by pbelbin** [comment]
I've seen (googling javascript to typescript conversion) various approaches to having a project that introduces TypeScript into an existing project.

Often, they've used either the TypeScript 'tsc' or webpack to do the transpiling.

Is either of these the way you want to go with this, or, perhaps something else?

I'm kind of guessing the 'tsc' might be the way I'd try going initially, unless you specifically want something else.  please let me know.
